[phases.setup]
nixPkgs = ['python3', 'wkhtmltopdf']

[phases.build]
cmds = ['pip install -r requirements.txt']
[phases.setup]
nixPkgs = ['...', 'wkhtmltopdf']

[phases.build]
cmds = ['pip install -r requirements.txt']

[phases.start]
cmds = ['python app.py']
